name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'github-pages/**'
  schedule:
    # Runs at 00:00 UTC every Sunday (Once a week, to update svg stat badges)
    - cron: '0 0 * * 0'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build Website
        working-directory: github-pages
        run: |
          chmod +x build.sh
          ./build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './github-pages/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Purge GitHub Camo Cache
        uses: kevincobain2000/action-camo-purge@v1
